name: Build clang-format static

on:
  workflow_dispatch:
  push:

jobs:
  build-ubuntu:
    strategy:
      matrix:
        llvm_version: ["18.1.8", "19.1.7", "20.1.8"]
        architecture: ["x86_64"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          ref: llvmorg-${{ matrix.llvm_version }}
          path: llvm-project
          fetch-depth: 1
      
      - name: Set up tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake python3 build-essential zlib1g-dev libncurses5-dev libncursesw5-dev

      - name: Build clang-format static
        run: |
          cd llvm-project
          cmake -G Ninja -Bbuild -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_STATIC=true -DLLVM_ENABLE_PROJECTS=clang ./llvm
          cd build
          ninja clang-format

      - name: Upload clang-format binary
        uses: actions/upload-artifact@v3
        with:
          name: clang-format-ubuntu-${{ matrix.architecture }}-${{ matrix.llvm_version }}
          path: llvm-project/build/bin/clang-format